### ISSUE TITLE
Testing with PHPUNIT 9.3

### ISSUE THREAD

**Issue by gsneijd** [afilina/video-php-mocks#1]
Thank you for your explanation in your video. 

I've tried your testcode with PHPUNIT 9.3 and it seems that there is no $spy->getInvocations() anymore.

Error: Call to undefined method PHPUnit\Framework\MockObject\Rule\AnyInvokedCount::getInvocation()

Do you have any suggestions for a work around?

**Comment by afilina** [comment]
Thanks for reporting. I'll take a look this week.

**Comment by afilina** [comment]
Hi, unfortunately, this feature was dropped from PHPUnit and there is no workaround. I even tried restoring the original functionality, but my pull request got rejected: https://github.com/sebastianbergmann/phpunit/pull/4447

**Comment by afilina** [comment]
I found this article with a complete example of how to use a custom class that acts as a spy. It's a lot more involved than PHPUnit's old approach, but at least it works on the latest versions.
https://jmauerhan.wordpress.com/2018/10/04/the-5-types-of-test-doubles-and-how-to-create-them-in-phpunit/
